### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by XYZscratcher** [Bingxiusmall/ASCII_Art_Demo#1]
当时运行时的代码，xyz.jpg、D:\xyz真实存在，路径正确：
```python
from PIL import Image, ImageDraw, ImageFont
def get_image_char_picture(picture_path, saving_path, font_size=10, font_path=r"C:\Windows\Fonts\STKAITI.ttf"):
    ascii_char = list("$@B%8&WM#*oahkbdpqwmZO0QLCJUYXzcvunxrjft/\\|()1{}[]?-_+~<>i!lI;:,\"^`'. ")
    img = Image.open(picture_path)
    w, h = img.size
    saving_img = Image.new("RGBA", (w, h))
    draw = ImageDraw.Draw(saving_img)
    font = ImageFont.truetype(font_path, font_size)
    for i in range(0, h, int(font_size / 2)):
        for j in range(0, w, int(font_size / 2)):
            r, g, b, a = img.getpixel((j, i))
            grey = (2126 * r + 7152 * g + 722 * b) / 10000
            if grey > 250:
                char = " "
            else:
                char = ascii_char[int(grey / len(ascii_char))]
            if char != " ":
                draw.text((j, i), char, fill=(r, g, b, a), font=font)
    saving_img.save(saving_path)
get_image_char_picture(‪E:\xyz.jpg, D:\xyz)

```

**Comment by Bingxiusmall** [comment]
我刚才在邮箱上回你了，再发一遍省得你没看到
怎么着也得用 `get_image_char_picture(‪r"E:\xyz.jpg", r"D:\xyz")` 吧，转义忘了就算了，居然连字符串形式都忘了就像是完全不会python似的……

**Comment by XYZscratcher** [comment]
还是报错：
```
OSError: [Errno 22] Invalid argument:'\u202aE:\\xyz.jpg'
```
怎么会多了一个\u202a？

**Comment by Bingxiusmall** [comment]
原因很简单，因为复制的时候前面多了一个U+202A，也就是【‪】，不过毕竟是隐字符，你看不出而已，把前面的这个字符去掉就行了

**Comment by XYZscratcher** [comment]
az，又出错了：
```Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\cs2.py", line 20, in <module>
    get_image_char_picture(r"E:\xyz.jpg",r"D:\xyz")
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\cs2.py", line 11, in get_image_char_picture
    r, g, b, a = img.getpixel((j, i))
ValueError: not enough values to unpack (expected 4, got 3)```

**Comment by Bingxiusmall** [comment]
哦，你这个是因为jpg图像只有rgb，没有a，等我改一下哈

**Comment by XYZscratcher** [comment]
好的，感谢你能耐心地解决我的问题，已经给你star了

**Comment by Bingxiusmall** [comment]
我终于改好了，你去看看吧（正在发，发完了就可以支持其他格式了

**Comment by Bingxiusmall** [comment]
Readme.md更新了，现在需要numpy了，install和import的方法都在那里面了

**Comment by XYZscratcher** [comment]
NB!
终于没有报错了！

**Comment by Bingxiusmall** [comment]
话说既然ok了把生成结果晒出来给我康康？（）

**Comment by XYZscratcher** [comment]
http://xyz.freeee.ml/cs.png
随便找了一个广告照片(doge

**Comment by Bingxiusmall** [comment]
az

**Comment by Bingxiusmall** [comment]
你得用：
get_image_char_picture(r"‪E:\xyz.jpg", r"D:\xyz.png")
不写成字符串形式有点太那啥了，像是完全不会python似的……



在 2022-08-04 13:51:41，"XYZscratcher" ***@***.***> 写道：

当时运行时的代码，xyz.jpg、D:\xyz真实存在，路径正确：

fromPILimportImage, ImageDraw, ImageFontdefget_image_char_picture(picture_path, saving_path, font_size=10, font_path=r"C:\Windows\Fonts\STKAITI.ttf"):

    ***@***.***%8&WM#*oahkbdpqwmZO0QLCJUYXzcvunxrjft/\\|()1{}[]?-_+~<>i!lI;:,\"^`'. ")

    img=Image.open(picture_path)

    w, h=img.sizesaving_img=Image.new("RGBA", (w, h))

    draw=ImageDraw.Draw(saving_img)

    font=ImageFont.truetype(font_path, font_size)

    foriinrange(0, h, int(font_size/2)):

        forjinrange(0, w, int(font_size/2)):

            r, g, b, a=img.getpixel((j, i))

            grey= (2126*r+7152*g+722*b) /10000ifgrey>250:

                char=" "else:

                char=ascii_char[int(grey/len(ascii_char))]

            ifchar!=" ":

                draw.text((j, i), char, fill=(r, g, b, a), font=font)

    saving_img.save(saving_path)

get_image_char_picture(‪E:\xyz.jpg, D:\xyz)
